### ISSUE TITLE
Allow overriding the name of the ecommerce OAuth2 application

### ISSUE THREAD

**Issue by lgp171188** [open-craft/microsite-generator#2]
This is useful because the default ecommerce OAuth2 application's redirect URIs are rewritten after every redeployment. So having a separate custom ecommerce OAuth2 application will solve that problem.

Currently, the name is hardcoded in `scripts/const.py`.

**Comment by shimulch** [comment]
@lgp171188, We can't use `ecommerce-sso` client anyway, because every deployment is going to override it. We can just use our own custom OAuth2 client name instead. Say - `multisite-ecommerce-sso`. While running the script, it will check if that exists or otherwise create that.

I don't think keeping it hardcoded is an issue. Is there any situation where we might want to override `multisite-ecommerce-sso`? If not we can just go with the new name and create it if not exist.

**Comment by lgp171188** [comment]
@shimulch, naming things is a hard problem - for example, I created a client with name `custom-sites-ecommerce-sso` 😛 . So, why not make it configurable with a reasonable default?

**Comment by shimulch** [comment]
@lgp171188  this fixed in https://github.com/open-craft/microsite-generator/pull/3
